# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-validations-ext}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Piotr Solnica"]
  s.date = %q{2010-10-22}
  s.description = %q{DataMapper plugin providing better error messages handling.}
  s.email = %q{piotr.solnica [a] gmail [d] com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "dm-validations-ext.gemspec",
     "lib/dm-validations-ext.rb",
     "spec/public/validations_ext_spec.rb",
     "spec/rcov.opts",
     "spec/spec_helper.rb",
     "tasks/ci.rake",
     "tasks/local_gemfile.rake",
     "tasks/metrics.rake",
     "tasks/spec.rake",
     "tasks/yard.rake",
     "tasks/yardstick.rake"
  ]
  s.has_rdoc = %q{yard}
  s.homepage = %q{http://github.com/solnic/dm-validations-ext}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{DataMapper plugin providing better error messages handling.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/public/validations_ext_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-validations>, ["~> 1.0.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.4"])
    else
      s.add_dependency(%q<dm-validations>, ["~> 1.0.2"])
      s.add_dependency(%q<rspec>, ["~> 2.0.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.4"])
    end
  else
    s.add_dependency(%q<dm-validations>, ["~> 1.0.2"])
    s.add_dependency(%q<rspec>, ["~> 2.0.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.4"])
  end
end

